# .github/workflows/pypi-health.yml
name: Check PyPI Health

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Check PyPI
        run: |
          echo "Checking https://pypi.jetson-ai-lab.dev/jp6/ ..."
          if curl -s -o /dev/null -w "%{http_code}" https://pypi.jetson-ai-lab.dev/jp6/ | grep -q "^2"; then
            echo "✅ PyPI is UP"
            echo '{"schemaVersion":1,"label":"Jetson PyPI","message":"up","color":"brightgreen"}' > health.json
          else
            echo "❌ PyPI is DOWN"
            echo '{"schemaVersion":1,"label":"Jetson PyPI","message":"down","color":"red"}' > health.json
          fi
      - name: Publish to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GH_PAT }}
          publish_dir: ./
          publish_branch: gh-pages
